default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: <%= Rails.application.secrets.database[:host] %>
  port: <%= Rails.application.secrets.database[:port] %>
  database: <%= Rails.application.secrets.database[:database] %>
  username: <%= Rails.application.secrets.database[:username] %>
  password: <%= Rails.application.secrets.database[:password] %>

test:
  <<: *default
  host: <%= Rails.application.secrets.database[:host] %>
  port: <%= Rails.application.secrets.database[:port] %>
  database: <%= Rails.application.secrets.database[:database] %>
  username: <%= Rails.application.secrets.database[:username] %>
  password: <%= Rails.application.secrets.database[:password] %>

production:
  <<: *default
  host: <%= Rails.application.secrets.database[:host] %>
  port: <%= Rails.application.secrets.database[:port] %>
  database: <%= Rails.application.secrets.database[:database] %>
  username: <%= Rails.application.secrets.database[:username] %>
  password: <%= Rails.application.secrets.database[:password] %>
